const languageArray = [
    { isoCode: "aa", language: "Afar" },
    { isoCode: "ab", language: "Abkhazian" },
    { isoCode: "ae", language: "Avestan" },
    { isoCode: "af", language: "Afrikaans" },
    { isoCode: "ak", language: "Akan" },
    { isoCode: "am", language: "Amharic" },
    { isoCode: "an", language: "Aragonese" },
    { isoCode: "ar", language: "Arabic" },
    { isoCode: "as", language: "Assamese" },
    { isoCode: "av", language: "Avaric" },
    { isoCode: "ay", language: "Aymara" },
    { isoCode: "az", language: "Azerbaijani" },
    { isoCode: "ba", language: "Bashkir" },
    { isoCode: "be", language: "Belarusian" },
    { isoCode: "bg", language: "Bulgarian" },
    { isoCode: "bh", language: "Bihari languages" },
    { isoCode: "bi", language: "Bislama" },
    { isoCode: "bm", language: "Bambara" },
    { isoCode: "bn", language: "Bengali" },
    { isoCode: "bo", language: "Tibetan" },
    { isoCode: "br", language: "Breton" },
    { isoCode: "bs", language: "Bosnian" },
    { isoCode: "ca", language: "Catalan; Valencian" },
    { isoCode: "ce", language: "Chechen" },
    { isoCode: "ch", language: "Chamorro" },
    { isoCode: "co", language: "Corsican" },
    { isoCode: "cr", language: "Cree" },
    { isoCode: "cs", language: "Czech" },
    { isoCode: "cu", language: "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic" },
    { isoCode: "cv", language: "Chuvash" },
    { isoCode: "cy", language: "Welsh" },
    { isoCode: "da", language: "Danish" },
    { isoCode: "de", language: "German" },
    { isoCode: "dv", language: "Divehi; Dhivehi; Maldivian" },
    { isoCode: "dz", language: "Dzongkha" },
    { isoCode: "ee", language: "Ewe" },
    { isoCode: "el", language: "Greek, Modern (1453-)" },
    { isoCode: "en", language: "English" },
    { isoCode: "eo", language: "Esperanto" },
    { isoCode: "es", language: "Spanish; Castilian" },
    { isoCode: "et", language: "Estonian" },
    { isoCode: "eu", language: "Basque" },
    { isoCode: "fa", language: "Persian" },
    { isoCode: "ff", language: "Fulah" },
    { isoCode: "fi", language: "Finnish" },
    { isoCode: "fj", language: "Fijian" },
    { isoCode: "fo", language: "Faroese" },
    { isoCode: "fr", language: "French" },
    { isoCode: "fy", language: "Western Frisian" },
    { isoCode: "ga", language: "Irish" },
    { isoCode: "gd", language: "Gaelic; Scottish Gaelic" },
    { isoCode: "gl", language: "Galician" },
    { isoCode: "gn", language: "Guarani" },
    { isoCode: "gu", language: "Gujarati" },
    { isoCode: "gv", language: "Manx" },
    { isoCode: "ha", language: "Hausa" },
    { isoCode: "he", language: "Hebrew" },
    { isoCode: "hi", language: "Hindi" },
    { isoCode: "ho", language: "Hiri Motu" },
    { isoCode: "hr", language: "Croatian" },
    { isoCode: "ht", language: "Haitian; Haitian Creole" },
    { isoCode: "hu", language: "Hungarian" },
    { isoCode: "hy", language: "Armenian" },
    { isoCode: "hz", language: "Herero" },
    { isoCode: "ia", language: "Interlingua (International Auxiliary Language Association)" },
    { isoCode: "id", language: "Indonesian" },
    { isoCode: "ie", language: "Interlingue; Occidental" },
    { isoCode: "ig", language: "Igbo" },
    { isoCode: "ii", language: "Sichuan Yi; Nuosu" },
    { isoCode: "ik", language: "Inupiaq" },
    { isoCode: "io", language: "Ido" },
    { isoCode: "is", language: "Icelandic" },
    { isoCode: "it", language: "Italian" },
    { isoCode: "iu", language: "Inuktitut" },
    { isoCode: "ja", language: "Japanese" },
    { isoCode: "jv", language: "Javanese" },
    { isoCode: "ka", language: "Georgian" },
    { isoCode: "kg", language: "Kongo" },
    { isoCode: "ki", language: "Kikuyu; Gikuyu" },
    { isoCode: "kj", language: "Kuanyama; Kwanyama" },
    { isoCode: "kk", language: "Kazakh" },
    { isoCode: "kl", language: "Kalaallisut; Greenlandic" },
    { isoCode: "km", language: "Central Khmer" },
    { isoCode: "kn", language: "Kannada" },
    { isoCode: "ko", language: "Korean" },
    { isoCode: "kr", language: "Kanuri" },
    { isoCode: "ks", language: "Kashmiri" },
    { isoCode: "ku", language: "Kurdish" },
    { isoCode: "kv", language: "Komi" },
    { isoCode: "kw", language: "Cornish" },
    { isoCode: "ky", language: "Kirghiz; Kyrgyz" },
    { isoCode: "la", language: "Latin" },
    { isoCode: "lb", language: "Luxembourgish; Letzeburgesch" },
    { isoCode: "lg", language: "Ganda" },
    { isoCode: "li", language: "Limburgan; Limburger; Limburgish" },
    { isoCode: "ln", language: "Lingala" },
    { isoCode: "lo", language: "Lao" },
    { isoCode: "lt", language: "Lithuanian" },
    { isoCode: "lu", language: "Luba-Katanga" },
    { isoCode: "lv", language: "Latvian" },
    { isoCode: "mg", language: "Malagasy" },
    { isoCode: "mh", language: "Marshallese" },
    { isoCode: "mi", language: "Maori" },
    { isoCode: "mk", language: "Macedonian" },
    { isoCode: "ml", language: "Malayalam" },
    { isoCode: "mn", language: "Mongolian" },
    { isoCode: "mr", language: "Marathi" },
    { isoCode: "ms", language: "Malay" },
    { isoCode: "mt", language: "Maltese" },
    { isoCode: "my", language: "Burmese" },
    { isoCode: "na", language: "Nauru" },
    { isoCode: "nb", language: "Bokmål, Norwegian; Norwegian Bokmål" },
    { isoCode: "nd", language: "Ndebele, North; North Ndebele" },
    { isoCode: "ne", language: "Nepali" },
    { isoCode: "ng", language: "Ndonga" },
    { isoCode: "nl", language: "Dutch; Flemish" },
    { isoCode: "nn", language: "Norwegian Nynorsk; Nynorsk, Norwegian" },
    { isoCode: "no", language: "Norwegian" },
    { isoCode: "nr", language: "Ndebele, South; South Ndebele" },
    { isoCode: "nv", language: "Navajo; Navaho" },
    { isoCode: "ny", language: "Chichewa; Chewa; Nyanja" },
    { isoCode: "oc", language: "Occitan (post 1500); Provençal" },
    { isoCode: "oj", language: "Ojibwa" },
    { isoCode: "om", language: "Oromo" },
    { isoCode: "or", language: "Oriya" },
    { isoCode: "os", language: "Ossetian; Ossetic" },
    { isoCode: "pa", language: "Panjabi; Punjabi" },
    { isoCode: "pi", language: "Pali" },
    { isoCode: "pl", language: "Polish" },
    { isoCode: "ps", language: "Pushto; Pashto" },
    { isoCode: "pt", language: "Portuguese" },
    { isoCode: "qu", language: "Quechua" },
    { isoCode: "rm", language: "Romansh" },
    { isoCode: "rn", language: "Rundi" },
    { isoCode: "ro", language: "Romanian; Moldavian; Moldovan" },
    { isoCode: "ru", language: "Russian" },
    { isoCode: "rw", language: "Kinyarwanda" },
    { isoCode: "sa", language: "Sanskrit" },
    { isoCode: "sc", language: "Sardinian" },
    { isoCode: "sd", language: "Sindhi" },
    { isoCode: "se", language: "Northern Sami" },
    { isoCode: "sg", language: "Sango" },
    { isoCode: "si", language: "Sinhala; Sinhalese" },
    { isoCode: "sk", language: "Slovak" },
    { isoCode: "sl", language: "Slovenian" },
    { isoCode: "sm", language: "Samoan" },
    { isoCode: "sn", language: "Shona" },
    { isoCode: "so", language: "Somali" },
    { isoCode: "sq", language: "Albanian" },
    { isoCode: "sr", language: "Serbian" },
    { isoCode: "ss", language: "Swati" },
    { isoCode: "st", language: "Sotho, Southern" },
    { isoCode: "su", language: "Sundanese" },
    { isoCode: "sv", language: "Swedish" },
    { isoCode: "sw", language: "Swahili" },
    { isoCode: "ta", language: "Tamil" },
    { isoCode: "te", language: "Telugu" },
    { isoCode: "tg", language: "Tajik" },
    { isoCode: "th", language: "Thai" },
    { isoCode: "ti", language: "Tigrinya" },
    { isoCode: "tk", language: "Turkmen" },
    { isoCode: "tl", language: "Tagalog" },
    { isoCode: "tn", language: "Tswana" },
    { isoCode: "to", language: "Tonga (Tonga Islands)" },
    { isoCode: "tr", language: "Turkish" },
    { isoCode: "ts", language: "Tsonga" },
    { isoCode: "tt", language: "Tatar" },
    { isoCode: "tw", language: "Twi" },
    { isoCode: "ty", language: "Tahitian" },
    { isoCode: "ug", language: "Uighur; Uyghur" },
    { isoCode: "uk", language: "Ukrainian" },
    { isoCode: "ur", language: "Urdu" },
    { isoCode: "uz", language: "Uzbek" },
    { isoCode: "ve", language: "Venda" },
    { isoCode: "vi", language: "Vietnamese" },
    { isoCode: "vo", language: "Volapük" },
    { isoCode: "wa", language: "Walloon" },
    { isoCode: "wo", language: "Wolof" },
    { isoCode: "xh", language: "Xhosa" },
    { isoCode: "yi", language: "Yiddish" },
    { isoCode: "yo", language: "Yoruba" },
    { isoCode: "za", language: "Zhuang; Chuang" },
    { isoCode: "zh", language: "Chinese" },
    { isoCode: "zu", language: "Zulu" },
]

module.exports = languageArray